name: Tests

on:
  push:
    branches-ignore:
      - master

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node_version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test
        env:
          GO_REST_ACCESS_TOKEN: ${{ secrets.GO_REST_ACCESS_TOKEN }}

